/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela.bolsa;

import dao.BolsaDAO;
import entidades.Bolsa;
import entidades.util.Validacao;
import tela.Principal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rlopes
 */
public class TelaCadastrarBolsa extends javax.swing.JInternalFrame {

    Principal principal;

    void limparCampos() {
        campoNomeBolsa.setText("");
    }

    private void desativarCampos() {
        campoNomeBolsa.setEnabled(false);
    }

    private void ativarCampos() {
        campoNomeBolsa.setEnabled(true);
    }

    public void editar() {
        limparCampos();
        ativarCampos();
        int linha = tabelaListarBolsa.getSelectedRow();
        campoNomeBolsa.setText(tabelaListarBolsa.getValueAt(linha, 1).toString());
    }

    public void salvarBolsa() {
        Bolsa bolsa = new Bolsa();
        bolsa.setNome(campoNomeBolsa.getText());
        int linhaSelecionada = tabelaListarBolsa.getSelectedRow();
        if (linhaSelecionada == -1) {
            try {
                bolsa.cadastrarBolsa(bolsa);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastrarBolsa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            bolsa.setId(Integer.parseInt(tabelaListarBolsa.getValueAt(linhaSelecionada, 0).toString()));
            try {
                bolsa.atualizarBolsa(bolsa);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastrarBolsa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            listarSetor();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarBolsa.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();
    }

    private void deletar() {
        Bolsa bolsa = new Bolsa();
        int linha = tabelaListarBolsa.getSelectedRow();
        bolsa.setId(Integer.parseInt(tabelaListarBolsa.getValueAt(linha, 0).toString()));
        try {
            bolsa.deletarBolsa();
            listarSetor();
            limparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarBolsa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void listarSetor() throws SQLException {
        ArrayList<Bolsa> vetorBolsa = new ArrayList<Bolsa>();
        BolsaDAO bolsaDAO = new BolsaDAO();
        Bolsa bolsa = new Bolsa();
        vetorBolsa = bolsaDAO.pesquisarTodasBolsas();
        DefaultTableModel meuModelo = (DefaultTableModel) tabelaListarBolsa.getModel();
        meuModelo.setNumRows(0);
        for (int i = 0; i < vetorBolsa.size(); i++) {
            meuModelo.addRow(bolsa.bolsaToLinha(vetorBolsa.get(i)));
        }
    }

    public void listarBolsa(String nome) throws SQLException {
        BolsaDAO bolsaDAO = new BolsaDAO();
        Bolsa bolsa = new Bolsa();
        Validacao validacao = new Validacao();
        DefaultTableModel meuModelo = (DefaultTableModel) tabelaListarBolsa.getModel();
        meuModelo.setNumRows(0);
        ArrayList<Bolsa> listaBolsa = new ArrayList<Bolsa>();
        listaBolsa = bolsaDAO.pesquisarBolsaPeloNome(nome);
        if (listaBolsa != null) {
            for (int i = 0; i < listaBolsa.size(); i++) {

                meuModelo.addRow(bolsa.bolsaToLinha(listaBolsa.get(i)));
            }
        } else {
            validacao.pesquisaErrada();
        }
    }

    public void atualizarTela() {
        this.repaint();
    }

    public void listarBolsa(int id) throws SQLException {

        BolsaDAO bolsaDAO = new BolsaDAO();
        Bolsa bolsa = new Bolsa();
        DefaultTableModel meuModelo = (DefaultTableModel) tabelaListarBolsa.getModel();
        meuModelo.setNumRows(0);
        bolsa = bolsaDAO.pesquisarBolsa(id);

        meuModelo.addRow(bolsa.bolsaToLinha(bolsa));
    }

    public void zerarTabelaBolsa() {
        DefaultTableModel meuModelo = (DefaultTableModel) tabelaListarBolsa.getModel();
        meuModelo.setNumRows(0);
    }

    public TelaCadastrarBolsa(Principal principal) throws SQLException {
        this.principal = principal;
        initComponents();
        desativarCampos();
        jButton7.setToolTipText("Novo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeBolsa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarBolsa = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1043, 649));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome Bolsa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar Bolsas");

        campoNomeBolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeBolsaActionPerformed(evt);
            }
        });

        tabelaListarBolsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaListarBolsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaListarBolsaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaListarBolsa);
        if (tabelaListarBolsa.getColumnModel().getColumnCount() > 0) {
            tabelaListarBolsa.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.setToolTipText("Pesquisar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new.png"))); // NOI18N
        jButton7.setText("Novo");
        jButton7.setToolTipText("Novo");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.setToolTipText("Salvar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jButton5.setText("Editar");
        jButton5.setToolTipText("Editar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list.png"))); // NOI18N
        jButton2.setText("Listar");
        jButton2.setToolTipText("Listar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        jButton8.setText("Limpar");
        jButton8.setToolTipText("Limpar");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixeira.png"))); // NOI18N
        jButton3.setText("Deletar");
        jButton3.setToolTipText("Deletar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButton6.setText("Fechar");
        jButton6.setToolTipText("Fechar");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tabela de Bolsas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(campoNomeBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNomeBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 1029, 604);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeBolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeBolsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeBolsaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        salvarBolsa();
        desativarCampos();
        limparCampos();
        //this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            desativarCampos();
            listarSetor();
            limparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastrarBolsa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        desativarCampos();
        deletar();
        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaListarBolsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListarBolsaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaListarBolsaMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        principal.exibirTelaPesquisarBolsa();
        desativarCampos();
        limparCampos();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        limparCampos();
        ativarCampos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        editar();
        //  jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        desativarCampos();
        limparCampos();
        zerarTabelaBolsa();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        principal.fecharTelaCadastrarBolsa();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomeBolsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabelaListarBolsa;
    // End of variables declaration//GEN-END:variables
}
